with 

source as (

    select * from {{ source('CASHIN_CASHOUT', 'receber_completa') }}

),

renamed as (

    select
        bukrs,
        fiscper,
        belnr,
        buzei,
        uposz,
        statusps,
        kunnr,
        kkber,
        maber,
        koart,
        umskz,
        blart,
        bschl,
        fiscvar,
        bldat,
        budat,
        cpudt,
        augdt,
        madat,
        netdt,
        sk1dt,
        sk2dt,
        zfbdt,
        zbd1t,
        zbd2t,
        zbd3t,
        zbd1p,
        zbd2p,
        land1,
        zlsch,
        zterm,
        zlspr,
        rstgr,
        mansp,
        mschl,
        manst,
        lcurr,
        dmsol,
        dmhab,
        dmshb,
        sknto,
        waers,
        wrsol,
        wrhab,
        wrshb,
        skfbt,
        wskto,
        ktopl,
        hkont,
        saknr,
        filkd,
        augbl,
        xblnr,
        rebzg,
        rebzj,
        rebzz,
        vbeln,
        xref1,
        xref2,
        xref3,
        sgtxt,
        xnegp,
        xarch,
        umsks,
        updmod,
        zuonr,
        awtyp,
        awkey,
        bstat,
        dmbtr,
        dmbe2,
        dmbe3,
        gjahr,
        hwae2,
        hwae3,
        monat,
        projk,
        shkzg,
        wrbtr,
        gsber,
        werks,
        zzpvrtnr,
        zzship_to,
        zzsegment,
        zzprctr,
        zzkursf,
        zzstblg,
        odq_changemode,
        odq_entitycntr

    from source

)

select * from renamed